"use client";

import { Header } from "@/components/header";
import { Modal, FormField, FormInput, FormSelect } from "@/components/modal";
import { useToast } from "@/components/toast";
import { ChevronLeft, ChevronRight, Loader2, Plus, Check, AlertTriangle } from "lucide-react";
import { useState } from "react";
import useSWR from "swr";

type AdminEvent = {
  id: string;
  title: string;
  description: string | null;
  dueDate: string;
  category: string;
  priority: string;
  isCompleted: boolean;
  completedAt: string | null;
  assignee: string | null;
  sourceType: string | null;
  sourceId: string | null;
  isAutoGenerated: boolean;
};

const categoryConfig: Record<string, { label: string; color: string; dot: string }> = {
  CONTRACT_RENEWAL: { label: "契約更新", color: "bg-red-100 text-red-800 border-red-300", dot: "bg-red-500" },
  INSPECTION: { label: "点検・車検", color: "bg-yellow-100 text-yellow-800 border-yellow-300", dot: "bg-yellow-500" },
  FILING: { label: "届出", color: "bg-purple-100 text-purple-800 border-purple-300", dot: "bg-purple-500" },
  PAYMENT: { label: "支払期限", color: "bg-blue-100 text-blue-800 border-blue-300", dot: "bg-blue-500" },
  CUSTOM: { label: "カスタム", color: "bg-gray-100 text-gray-700 border-gray-300", dot: "bg-gray-500" },
};

const priorityLabels: Record<string, { label: string; color: string }> = {
  LOW: { label: "低", color: "text-gray-500" },
  MEDIUM: { label: "中", color: "text-yellow-600" },
  HIGH: { label: "高", color: "text-orange-600" },
  URGENT: { label: "緊急", color: "text-red-600" },
};

const weekDays = ["日", "月", "火", "水", "木", "金", "土"];

function getDaysInMonth(year: number, month: number) { return new Date(year, month + 1, 0).getDate(); }
function getFirstDayOfWeek(year: number, month: number) { return new Date(year, month, 1).getDay(); }

const fetcher = (url: string) => fetch(url).then((r) => r.json());

export default function AdminCalendarPage() {
  const [currentYear, setCurrentYear] = useState(2026);
  const [currentMonth, setCurrentMonth] = useState(2);
  const [categoryFilter, setCategoryFilter] = useState("");
  const [showCompleted, setShowCompleted] = useState(false);
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [showNewModal, setShowNewModal] = useState(false);
  const [newForm, setNewForm] = useState({
    title: "", description: "", dueDate: "", category: "CUSTOM", priority: "MEDIUM", assignee: "", note: "",
  });
  const { showToast } = useToast();

  const apiMonth = currentMonth + 1;

  const { data: eventData, isLoading, mutate } = useSWR<{ events: AdminEvent[] }>(
    `/api/calendar/admin?year=${currentYear}&month=${apiMonth}${categoryFilter ? `&category=${categoryFilter}` : ""}&includeCompleted=${showCompleted}`,
    fetcher
  );

  const events = eventData?.events ?? [];

  const daysInMonth = getDaysInMonth(currentYear, currentMonth);
  const firstDay = getFirstDayOfWeek(currentYear, currentMonth);

  const getEventsForDay = (day: number): AdminEvent[] => {
    const dateStr = `${currentYear}-${String(apiMonth).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
    return events.filter((e) => e.dueDate === dateStr);
  };

  const goToPrevMonth = () => {
    if (currentMonth === 0) { setCurrentYear(currentYear - 1); setCurrentMonth(11); }
    else setCurrentMonth(currentMonth - 1);
  };
  const goToNextMonth = () => {
    if (currentMonth === 11) { setCurrentYear(currentYear + 1); setCurrentMonth(0); }
    else setCurrentMonth(currentMonth + 1);
  };

  const handleCreate = async () => {
    if (!newForm.title || !newForm.dueDate) { showToast("タイトルと日付は必須です", "error"); return; }
    try {
      const res = await fetch("/api/calendar/admin", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(newForm),
      });
      if (!res.ok) throw new Error("Failed");
      setShowNewModal(false);
      setNewForm({ title: "", description: "", dueDate: "", category: "CUSTOM", priority: "MEDIUM", assignee: "", note: "" });
      mutate();
      showToast("予定を追加しました", "success");
    } catch { showToast("追加に失敗しました", "error"); }
  };

  const handleToggleComplete = async (evt: AdminEvent) => {
    if (evt.isAutoGenerated) return; // 自動生成は変更不可
    try {
      const res = await fetch(`/api/calendar/admin/${evt.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ isCompleted: !evt.isCompleted }),
      });
      if (!res.ok) throw new Error("Failed");
      mutate();
      showToast(evt.isCompleted ? "未完了に戻しました" : "完了にしました", "success");
    } catch { showToast("更新に失敗しました", "error"); }
  };

  const handleDelete = async (evt: AdminEvent) => {
    if (evt.isAutoGenerated) return;
    if (!confirm("この予定を削除しますか？")) return;
    try {
      const res = await fetch(`/api/calendar/admin/${evt.id}`, { method: "DELETE" });
      if (!res.ok) throw new Error("Failed");
      setSelectedDate(null);
      mutate();
      showToast("削除しました", "success");
    } catch { showToast("削除に失敗しました", "error"); }
  };

  const selectedEvents = selectedDate ? events.filter((e) => e.dueDate === selectedDate) : [];
  const todayStr = new Date().toISOString().split("T")[0];

  // 未完了ToDoリスト（期限順）
  const todoList = events.filter((e) => !e.isCompleted).sort((a, b) => a.dueDate.localeCompare(b.dueDate));

  return (
    <>
      <Header title="管理カレンダー" />
      <div className="p-4 md:p-6 space-y-4">
        {/* フィルタ */}
        <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div className="flex items-center gap-2 flex-wrap">
            <select
              value={categoryFilter}
              onChange={(e) => setCategoryFilter(e.target.value)}
              className="px-3 py-2 text-sm border border-border rounded-lg bg-surface"
            >
              <option value="">全カテゴリ</option>
              {Object.entries(categoryConfig).map(([key, cfg]) => (
                <option key={key} value={key}>{cfg.label}</option>
              ))}
            </select>
            <label className="flex items-center gap-1.5 text-sm text-text-secondary">
              <input
                type="checkbox"
                checked={showCompleted}
                onChange={(e) => setShowCompleted(e.target.checked)}
                className="rounded border-border"
              />
              完了も表示
            </label>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={goToPrevMonth} className="p-2 hover:bg-surface-tertiary rounded-lg"><ChevronLeft className="w-5 h-5 text-text-secondary" /></button>
            <h2 className="text-lg font-bold text-text">{currentYear}年 {apiMonth}月</h2>
            <button onClick={goToNextMonth} className="p-2 hover:bg-surface-tertiary rounded-lg"><ChevronRight className="w-5 h-5 text-text-secondary" /></button>
            <button
              onClick={() => { setNewForm({ ...newForm, dueDate: todayStr }); setShowNewModal(true); }}
              className="flex items-center gap-2 px-4 py-2 text-sm bg-primary-600 text-text-inverse rounded-lg font-medium hover:bg-primary-700 transition-colors ml-2"
            >
              <Plus className="w-4 h-4" />予定追加
            </button>
          </div>
        </div>

        {/* 凡例 */}
        <div className="flex items-center gap-4 flex-wrap">
          {Object.entries(categoryConfig).map(([key, cfg]) => (
            <div key={key} className="flex items-center gap-1.5">
              <span className={`w-3 h-3 rounded-full ${cfg.dot}`} />
              <span className="text-xs text-text-secondary">{cfg.label}</span>
            </div>
          ))}
        </div>

        {/* カレンダー */}
        {isLoading ? (
          <div className="flex items-center justify-center h-64">
            <Loader2 className="w-8 h-8 animate-spin text-primary-600" />
          </div>
        ) : (
          <div className="bg-surface rounded-xl border border-border overflow-x-auto">
            <div className="grid grid-cols-7 border-b border-border">
              {weekDays.map((day, i) => (
                <div key={day} className={`px-2 py-2 text-center text-xs font-medium ${i === 0 ? "text-red-500" : i === 6 ? "text-blue-500" : "text-text-secondary"} bg-surface-secondary`}>
                  {day}
                </div>
              ))}
            </div>
            <div className="grid grid-cols-7">
              {Array.from({ length: firstDay }).map((_, i) => (
                <div key={`empty-${i}`} className="min-h-[60px] md:min-h-[100px] border-b border-r border-border bg-surface-secondary/30" />
              ))}
              {Array.from({ length: daysInMonth }).map((_, i) => {
                const day = i + 1;
                const dayOfWeek = (firstDay + i) % 7;
                const dayEvents = getEventsForDay(day);
                const today = new Date();
                const isToday = today.getFullYear() === currentYear && today.getMonth() === currentMonth && today.getDate() === day;
                const dateStr = `${currentYear}-${String(apiMonth).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
                const hasOverdue = dayEvents.some((e) => !e.isCompleted && dateStr < todayStr);

                return (
                  <button
                    key={day}
                    onClick={() => setSelectedDate(dateStr)}
                    className={`min-h-[60px] md:min-h-[100px] border-b border-r border-border p-1.5 text-left hover:bg-primary-50/30 transition-colors ${
                      isToday ? "bg-primary-50/50" : hasOverdue ? "bg-red-50/50" : ""
                    }`}
                  >
                    <span className={`inline-flex w-6 h-6 items-center justify-center text-xs rounded-full ${
                      isToday ? "bg-primary-600 text-white font-bold" :
                      dayOfWeek === 0 ? "text-red-500" : dayOfWeek === 6 ? "text-blue-500" : "text-text-secondary"
                    }`}>{day}</span>
                    <div className="mt-1 flex items-center gap-0.5 flex-wrap">
                      {dayEvents.slice(0, 4).map((evt) => {
                        const cfg = categoryConfig[evt.category] ?? categoryConfig.CUSTOM;
                        return (
                          <span key={evt.id} className={`w-2 h-2 rounded-full ${evt.isCompleted ? "bg-gray-300" : cfg.dot}`} title={evt.title} />
                        );
                      })}
                      {dayEvents.length > 0 && (
                        <span className="text-[10px] text-text-tertiary ml-0.5">{dayEvents.length}</span>
                      )}
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {/* 未完了ToDoリスト */}
        {todoList.length > 0 && (
          <div className="bg-surface rounded-xl border border-border p-4">
            <h3 className="text-sm font-bold text-text mb-3 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-orange-500" />
              未完了タスク ({todoList.length}件)
            </h3>
            <div className="space-y-2 max-h-64 overflow-y-auto">
              {todoList.map((evt) => {
                const cfg = categoryConfig[evt.category] ?? categoryConfig.CUSTOM;
                const isOverdue = evt.dueDate < todayStr;
                const pri = priorityLabels[evt.priority] ?? priorityLabels.MEDIUM;
                return (
                  <div key={evt.id} className={`flex items-center gap-3 p-2 rounded-lg border ${isOverdue ? "border-red-300 bg-red-50" : "border-border"}`}>
                    {!evt.isAutoGenerated && (
                      <button onClick={() => handleToggleComplete(evt)} className="shrink-0 w-5 h-5 rounded border border-border hover:border-primary-500 flex items-center justify-center">
                        {evt.isCompleted && <Check className="w-3 h-3 text-primary-600" />}
                      </button>
                    )}
                    <span className={`w-2 h-2 rounded-full shrink-0 ${cfg.dot}`} />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm text-text truncate">{evt.title}</p>
                      <p className="text-xs text-text-tertiary">{evt.dueDate} · <span className={pri.color}>{pri.label}</span>{evt.assignee && ` · ${evt.assignee}`}</p>
                    </div>
                    <span className={`text-[10px] px-1.5 py-0.5 rounded border ${cfg.color}`}>{cfg.label}</span>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* 日クリックモーダル */}
      <Modal
        isOpen={!!selectedDate}
        onClose={() => setSelectedDate(null)}
        title={selectedDate ? `${selectedDate} の予定` : ""}
        footer={
          <>
            <button
              onClick={() => { setNewForm({ ...newForm, dueDate: selectedDate ?? todayStr }); setSelectedDate(null); setShowNewModal(true); }}
              className="px-4 py-2 text-sm border border-border rounded-lg text-text-secondary hover:bg-surface-tertiary"
            >
              <Plus className="w-4 h-4 inline mr-1" />追加
            </button>
            <button onClick={() => setSelectedDate(null)} className="px-4 py-2 text-sm bg-primary-600 text-text-inverse rounded-lg font-medium hover:bg-primary-700">閉じる</button>
          </>
        }
      >
        {selectedEvents.length > 0 ? (
          <div className="space-y-2 max-h-[60vh] overflow-y-auto">
            {selectedEvents.map((evt) => {
              const cfg = categoryConfig[evt.category] ?? categoryConfig.CUSTOM;
              const pri = priorityLabels[evt.priority] ?? priorityLabels.MEDIUM;
              return (
                <div key={evt.id} className={`p-3 rounded-lg border ${evt.isCompleted ? "bg-surface-secondary border-border opacity-60" : cfg.color}`}>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-medium">{cfg.label} · <span className={pri.color}>{pri.label}</span></span>
                    <div className="flex items-center gap-1">
                      {!evt.isAutoGenerated && (
                        <>
                          <button onClick={() => handleToggleComplete(evt)} className="p-1 hover:bg-white/50 rounded" title={evt.isCompleted ? "未完了に戻す" : "完了にする"}>
                            <Check className={`w-3.5 h-3.5 ${evt.isCompleted ? "text-green-600" : "text-text-tertiary"}`} />
                          </button>
                          <button onClick={() => handleDelete(evt)} className="p-1 hover:bg-white/50 rounded text-red-400 text-xs">削除</button>
                        </>
                      )}
                      {evt.isAutoGenerated && <span className="text-[10px] text-text-tertiary">自動</span>}
                    </div>
                  </div>
                  <p className="text-sm font-medium">{evt.title}</p>
                  {evt.description && <p className="text-xs mt-1">{evt.description}</p>}
                  {evt.assignee && <p className="text-xs mt-1">担当: {evt.assignee}</p>}
                </div>
              );
            })}
          </div>
        ) : (
          <p className="text-sm text-text-tertiary text-center py-8">この日の予定はありません</p>
        )}
      </Modal>

      {/* 予定追加モーダル */}
      <Modal
        isOpen={showNewModal}
        onClose={() => setShowNewModal(false)}
        title="予定追加"
        footer={
          <>
            <button onClick={() => setShowNewModal(false)} className="px-4 py-2 text-sm border border-border rounded-lg text-text-secondary hover:bg-surface-tertiary">キャンセル</button>
            <button onClick={handleCreate} className="px-4 py-2 text-sm bg-primary-600 text-text-inverse rounded-lg font-medium hover:bg-primary-700">追加する</button>
          </>
        }
      >
        <div className="space-y-4">
          <FormField label="タイトル" required><FormInput value={newForm.title} onChange={(e) => setNewForm({ ...newForm, title: e.target.value })} /></FormField>
          <FormField label="日付" required><FormInput type="date" value={newForm.dueDate} onChange={(e) => setNewForm({ ...newForm, dueDate: e.target.value })} /></FormField>
          <FormField label="カテゴリ">
            <FormSelect
              value={newForm.category}
              onChange={(e) => setNewForm({ ...newForm, category: e.target.value })}
              options={Object.entries(categoryConfig).map(([k, v]) => ({ value: k, label: v.label }))}
            />
          </FormField>
          <FormField label="優先度">
            <FormSelect
              value={newForm.priority}
              onChange={(e) => setNewForm({ ...newForm, priority: e.target.value })}
              options={Object.entries(priorityLabels).map(([k, v]) => ({ value: k, label: v.label }))}
            />
          </FormField>
          <FormField label="担当者"><FormInput value={newForm.assignee} onChange={(e) => setNewForm({ ...newForm, assignee: e.target.value })} /></FormField>
          <FormField label="説明"><FormInput value={newForm.description} onChange={(e) => setNewForm({ ...newForm, description: e.target.value })} /></FormField>
          <FormField label="メモ"><FormInput value={newForm.note} onChange={(e) => setNewForm({ ...newForm, note: e.target.value })} /></FormField>
        </div>
      </Modal>
    </>
  );
}
