import { prisma } from "@/lib/db";
import { validateBody } from "@/lib/validate";
import { adminCalendarEventCreate } from "@/lib/schemas";
import { cacheHeaders } from "@/lib/cache";
import { NextRequest, NextResponse } from "next/server";
import { withErrorHandler } from "@/lib/api-error-handler";
import { createAuditLog } from "@/lib/audit";

type AdminEvent = {
  id: string;
  title: string;
  description: string | null;
  dueDate: string;
  category: string;
  priority: string;
  isCompleted: boolean;
  completedAt: string | null;
  assignee: string | null;
  sourceType: string | null;
  sourceId: string | null;
  isAutoGenerated: boolean;
};

export const GET = withErrorHandler(async (request: NextRequest) => {
  const { searchParams } = new URL(request.url);
  const year = parseInt(searchParams.get("year") ?? new Date().getFullYear().toString());
  const month = parseInt(searchParams.get("month") ?? (new Date().getMonth() + 1).toString());
  const category = searchParams.get("category");
  const includeCompleted = searchParams.get("includeCompleted") === "true";

  const startDate = new Date(year, month - 1, 1);
  const endDate = new Date(year, month, 0, 23, 59, 59);

  const events: AdminEvent[] = [];

  // A. 手動登録イベント
  const manualWhere: Record<string, unknown> = {
    dueDate: { gte: startDate, lte: endDate },
  };
  if (category) manualWhere.category = category;
  if (!includeCompleted) manualWhere.isCompleted = false;

  const manualEvents = await prisma.adminCalendarEvent.findMany({
    where: manualWhere,
    orderBy: { dueDate: "asc" },
  });

  for (const e of manualEvents) {
    events.push({
      id: e.id,
      title: e.title,
      description: e.description,
      dueDate: e.dueDate.toISOString().split("T")[0],
      category: e.category,
      priority: e.priority,
      isCompleted: e.isCompleted,
      completedAt: e.completedAt?.toISOString() ?? null,
      assignee: e.assignee,
      sourceType: e.sourceType,
      sourceId: e.sourceId,
      isAutoGenerated: false,
    });
  }

  // B. 自動生成: 契約更新通知
  if (!category || category === "CONTRACT_RENEWAL") {
    const contracts = await prisma.contract.findMany({
      where: {
        status: "ACTIVE",
        endDate: { not: null },
      },
      include: {
        partner: { select: { name: true } },
      },
    });

    for (const c of contracts) {
      if (!c.endDate) continue;

      // 契約期限日
      const endDateStr = c.endDate.toISOString().split("T")[0];
      const endD = new Date(c.endDate);
      if (endD >= startDate && endD <= endDate) {
        events.push({
          id: `contract-end-${c.id}`,
          title: `契約期限: ${c.partner?.name ?? ""} - ${c.title}`,
          description: `契約番号: ${c.contractNumber}`,
          dueDate: endDateStr,
          category: "CONTRACT_RENEWAL",
          priority: "HIGH",
          isCompleted: false,
          completedAt: null,
          assignee: null,
          sourceType: "Contract",
          sourceId: c.id,
          isAutoGenerated: true,
        });
      }

      // 更新通知日（renewalNoticeDays前）
      if (c.renewalNoticeDays) {
        const noticeDate = new Date(c.endDate);
        noticeDate.setDate(noticeDate.getDate() - c.renewalNoticeDays);
        if (noticeDate >= startDate && noticeDate <= endDate) {
          events.push({
            id: `contract-notice-${c.id}`,
            title: `更新通知: ${c.partner?.name ?? ""} - ${c.title}`,
            description: `契約期限 ${endDateStr} の ${c.renewalNoticeDays}日前`,
            dueDate: noticeDate.toISOString().split("T")[0],
            category: "CONTRACT_RENEWAL",
            priority: "URGENT",
            isCompleted: false,
            completedAt: null,
            assignee: null,
            sourceType: "Contract",
            sourceId: c.id,
            isAutoGenerated: true,
          });
        }
      }
    }
  }

  // C. 自動生成: 支払期限（未払いInvoice）
  if (!category || category === "PAYMENT") {
    const invoices = await prisma.invoice.findMany({
      where: {
        dueDate: { gte: startDate, lte: endDate },
        status: { in: ["DRAFT", "ISSUED", "SENT"] },
      },
      include: {
        customer: { select: { name: true } },
      },
    });

    for (const inv of invoices) {
      if (!inv.dueDate) continue;
      events.push({
        id: `invoice-due-${inv.id}`,
        title: `支払期限: ${inv.customer?.name ?? ""} ${inv.invoiceNumber}`,
        description: `請求額: ¥${inv.total.toLocaleString()}`,
        dueDate: inv.dueDate.toISOString().split("T")[0],
        category: "PAYMENT",
        priority: "HIGH",
        isCompleted: false,
        completedAt: null,
        assignee: null,
        sourceType: "Invoice",
        sourceId: inv.id,
        isAutoGenerated: true,
      });
    }
  }

  // 日付順ソート
  events.sort((a, b) => a.dueDate.localeCompare(b.dueDate));

  return NextResponse.json({ events }, { headers: cacheHeaders("TRANSACTION") });
});

export const POST = withErrorHandler(async (request: NextRequest) => {
  const result = await validateBody(request, adminCalendarEventCreate);
  if ("error" in result) return result.error;
  const body = result.data as Record<string, unknown>;

  const record = await prisma.adminCalendarEvent.create({
    data: {
      title: body.title as string,
      description: body.description as string | undefined,
      dueDate: new Date(body.dueDate as string),
      category: body.category as string,
      priority: (body.priority as string) ?? "MEDIUM",
      assignee: body.assignee as string | undefined,
      note: body.note as string | undefined,
    },
  });

  await createAuditLog({ action: "CREATE", tableName: "AdminCalendarEvent", recordId: record.id, newData: record });

  return NextResponse.json(record, { status: 201 });
});
